### ISSUE TITLE
DD Search and Tool Registry not working on pdscloud-gamma

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-tasks#10]
## 🐛 Describe the bug

Looks like these are working on pdscloud-prod. Looks like the apps are calling the services explicitly (e.g. pds-gamma.jpl.nasa.gov/foobar) instead of just hitting `/foobar`. Once we do that, I think this should work.

If not, this may be a server config thing.

**Comment by jordanpadams** [comment]
@eddiesarevalo once we get the NPM package deployed, can you please help @c-suh here? she will provide some details about how to get to pdscloud-gamma

**Comment by c-suh** [comment]
for description:
![ScreenShot2022-01-24](https://user-images.githubusercontent.com/18314609/150862345-c7aa5d3b-e5dd-47da-953b-2df629889e0c.jpg)

@eddiesarevalo let me know if you need more details and information

**Comment by c-suh** [comment]
I changed the relevant files, updated the [Website Deployment documentation](https://wiki.jpl.nasa.gov/display/PDSEN/Website+Deployment+Procedure), and pulled the changes onto the PDS prem machines. The changes should be reflected on the AWS machines shortly.

**Comment by tloubrieu-jpl** [comment]
@gxtchen , since today the url to test this deployment is https://pds-gamma.jpl.nasa.gov/
