### ISSUE TITLE
tool registry search result count is incorrect

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/portal-tasks#102]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

- number of product per page (10) does not match the text Displaying ...
- the number of result is lower than it was before
- the radiobutton do not work

<img width="407" alt="Screenshot 2024-11-13 at 5 06 32 PM" src="https://github.com/user-attachments/assets/0aca74e4-0674-40af-963d-357c514fa686">

**Comment by jordanpadams** [comment]
@tloubrieu-jpl who identified this issue? And is anyone working it?

**Comment by tloubrieu-jpl** [comment]
Hi @Padams, Jordan H (US ***@***.***>, @Suh, Catherine (US ***@***.***>, @Arevalo, Eddie S (US ***@***.***>and @Natha, Anil (US ***@***.***>reported the issue at the standup yesterday. No one is working on it yet. We were thinking you would first give feedback on the priority level and some expertise on what might go wrong.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Jordan Padams ***@***.***>
Sent: Thursday, October 10, 2024 7:00:16 PM
To: NASA-PDS/portal-tasks ***@***.***>
Cc: Loubrieu, Thomas G (US 398F) ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [NASA-PDS/portal-tasks] tool registry does not completely work (Issue #102)


@tloubrieu-jpl<https://urldefense.us/v3/__https://github.com/tloubrieu-jpl__;!!PvBDto6Hs4WbVuu7!JVXuGFvYYKcsxs6q-MbjyFlfQIVxk059IExO06RhL7ZDX_hkjb6--VHfDXz5dzzNdcCSOQkFczJ1q_MFGWNOgVHHM_5YG4UMDOMA$> who identified this issue? And is anyone working it?

**Comment by c-suh** [comment]
For the first issue - the number of results always being 10 despite the counter saying otherwise (e.g., 1-50, 51-65) - the solution is to specify the rows parameter when setting the query for solr. I can provide the exact code and location or make the change myself (to __ branch); lmk which is preferable.

**Comment by c-suh** [comment]
The fix had already been pushed to its own branch, so I did the requisite merges, and it is now deployed at https://pds.nasa.gov/tools/tool-registry/.
