### ISSUE TITLE
Enhancements to pds-engineering website

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-tasks#11]
- [x] The App Bar is missing from the website when it moved to AWS

- [ ] Is there any way we can cleanup this footer? Some margin and cleanup would be great. Looks pretty funky on Chrome:
<img width="1278" alt="Screen Shot 2021-12-10 at 8 40 15 AM" src="https://user-images.githubusercontent.com/33492486/145609407-98d0e099-ebd5-40fd-8291-13a8858bc65d.png">

- [x] Remove "Get Newsletter" section of footer - I know this is part of the JPL template, but it makes no sense in the PDS context and is super confusing to our users. If anyone from URS pokes at this, please forward them on to me.

- [x] Update Curator name to Vivian

**Comment by c-suh** [comment]
@jordanpadams would you take a look again at the second item (cleaning up footer - margin and repeating FirstGov logo)? I don't see the repeating logo, and I'm not sure of spacing/margins after removal of the third item (Newsletter and Follow JPL).

**Comment by jordanpadams** [comment]
+1 looks good to go

**Comment by jordanpadams** [comment]
[ ] Can we add the new clearance number?  #22-1195

**Comment by jordanpadams** [comment]
@c-suh ☝️

**Comment by c-suh** [comment]
Clearance # updated.
