### ISSUE TITLE
CCB-325: Update MC Policies

### ISSUE THREAD

**Issue by viviant100** [NASA-PDS/portal-tasks#110]
## 💡 Description

- [x] Update "PDS Policy on Formats for PDS4 Data and Documentation (https://pds.nasa.gov/datastandards/documents/policy/format_policies_final.pdf) to allow these restricted formats for compressed video and/or audio science data and documentation (see format_policies_230222-1.docx).

- [x] Update the supplementary white paper (attached here, MP4-H264-ACC_v4.pdf) on use of compressed data to include video and audio science data. Include guidelines for setting Constant Quality (CRF) and audio bit rates. overwrite original found here: https://pds.nasa.gov/datastandards/documents/archiving/ . Probably best to change the title to:
> MP4:
> [Archiving Video (MP4: H.264 and AAC)](https://pds.nasa.gov/datastandards/documents/archiving/MP4-H264-ACC_v4.pdf)

- [x] Add requirements for DN tracking of encoded video and audio products, annual reporting, and assessment of format viability at least every five years (and transformation if not) to the existing policy on data integrity checking (https://pds.nasa.gov/datastandards/documents/policy/dataintegrity_checkingschedule_20080829.pdf) (see data_integrity_update_v2.docx).

**Comment by jordanpadams** [comment]
Refs https://github.com/NASA-PDS/PDS4-CCB/issues/19
