### ISSUE TITLE
Remove login from pds-engineering site

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-tasks#14]
## 💡 Description

Add new clearance number to footer (CL#22-1195) and then disable login screen as default landing page.

Pre-requisites:
- [x] figure out if there is anything we can do about that first gov image that looks really weird in the bottom bar. or can we just remove it altogether?

**Comment by c-suh** [comment]
New clearance number updated as part of https://github.com/NASA-PDS/portal-tasks/issues/11#issuecomment-1063658247. Login removal is still to be done.

**Comment by jordanpadams** [comment]
@c-suh added this to the sprint backlog as next up in the queue after the other tasks you are working on

**Comment by c-suh** [comment]
I believe login has been removed. Am testing.

Items to review:
- PDS3 Standards > [Blog](http://pdsdlb3.jpl.nasa.gov/pebble/)
- in general, PDS3 Standards needs to be reviewed

**Comment by tloubrieu-jpl** [comment]
@c-suh removed the login, @jordanpadams do you want to test ?

**Comment by jordanpadams** [comment]
@c-suh @tloubrieu-jpl looks good!
