### ISSUE TITLE
Update Build Schedule on website

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-tasks#15]
## 💡 Description

I know the schedule is here: https://pds.nasa.gov/datastandards/about/, and I think elsewhere? Wherever it is, we need to update with the next 4 builds.

Also, update to include letter abbreviations with each number, e.g.

| IM Version | Build Number | Release Date |
| ----------- | ------------- | ------------ | 
| 1.21.0.0 (1K00) |	14.1 | December 2023 |
| 1.20.0.0 (1K00) |	14.0 | June 2023 |
| 1.19.0.0 (1J00) |	13.1 | December 2022 |
| 1.18.0.0 (1I00) |	13.0 | June 2022 |

**Comment by c-suh** [comment]
@viviant100 the next 4 builds have been added to [Data Standards > About](https://pds.nasa.gov/datastandards/about/) and [Tools > About](https://pds.nasa.gov/tools/about/). I went ahead and changed 1.21.0.0 to 1L00 (not 1K00) and also tweaked the styling of the tables. It may not be pretty, but I think it's easier to read now, but let me know if you'd like me to change it back or change it in some other way.
