### ISSUE TITLE
Add processing levels document to Documents portal

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-tasks#20]
## 💡 Description

Add document from https://github.com/NASA-PDS/pds4-information-model/issues/415) to https://pds.nasa.gov/datastandards/documents/

https://github.com/NASA-PDS/pds4-information-model/issues/415#issuecomment-1029453883

**Comment by c-suh** [comment]
@viviant100 let me know the placement and wording for this new document, [ProcessingLevelsMapping_220202b.docx](https://github.com/NASA-PDS/pds4-information-model/files/7998639/ProcessingLevelsMapping_220202b.docx) (document from issue comment linked in the description).

**Comment by viviant100** [comment]
@c-suh Please add a new section after the "Information Model Specification" with the following :

- PDS4, NASA, CODMAC Processing Level Comparison
   This chart provides a guide to determine the most appropriate Processing Level to use when preparing PDS4 product labels.

Attached is the PDF version of the doc with red cross-out removed.

[ProcessingLevelsMapping_220202b.pdf](https://github.com/NASA-PDS/portal-tasks/files/8274774/ProcessingLevelsMapping_220202b.pdf)
