### ISSUE TITLE
Fix odd spacing in header for keyword search and data set status

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-tasks#22]
## 🐛 Describe the bug

See screenshots from https://pds.nasa.gov/datasearch/keyword-search/

<img width="1724" alt="Screen Shot 2022-04-03 at 10 09 15 AM" src="https://user-images.githubusercontent.com/33492486/161439548-509dc60f-c659-4a8f-b639-a4facd63b3da.png">

... and [Data Set Status](https://pds.nasa.gov/datasearch/ds-status/dsidStatus.jsp?sortOpt1=di.dsid&sortOpt2=&sortOpt3=&sortOpt4=&sortOpt5=&nodename=ALL&col2=di.archivestat&col3=&col4=&col5=&Go=Submit)

![Screen Shot 2022-04-05 at 10 23 29 AM](https://user-images.githubusercontent.com/18314609/161815690-607a20ed-9047-495e-84a4-6b8bc607e5f2.jpg)

**Comment by c-suh** [comment]
Updates have been made to the files, but it would be better to first repackage the .war files then redeploy these applications. From https://itsd-jira.jpl.nasa.gov/servicedesk/customer/portal/16/DSIO-1041, this might require restarting tomcat. Will test on the non-operational production machine and, if this is the case, will coordinate with Richard to make sure that wouldn't disrupt anything he might be running.
- Keyword Search: .war is ready
- Data Set Status: .war is not ready. Having another maven issue (again).

**Comment by c-suh** [comment]
.war packages created and re-deployed for both applications on all aws machines.
Keyword Search at https://pds.nasa.gov/datasearch/keyword-search/.
Data Set Status at https://pds.nasa.gov/datasearch/ds-status/.
