### ISSUE TITLE
Create documentation for pds.nasa.gov in AWS

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-tasks#23]
## 💡 Description

Update documentation here for new deployment in AWS for applications such as he DOI Service. All the docs are on the wiki, https://wiki.jpl.nasa.gov/display/PDSEN/Software+Installation+and+Deployment+Guides

**Comment by tloubrieu-jpl** [comment]
@c-suh has made good progress on that. The only remaining thing for this task is to make the page https://wiki.jpl.nasa.gov/display/PDSEN/Software+Installation+and+Deployment+Guides a table which summarized the currently deployed versions and the target infrastructure...

**Comment by c-suh** [comment]
Updated to table form with columns
- Software
- Version
- Host
- Other Documentation
