### ISSUE TITLE
add documents to Training page

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS/portal-tasks#24]
## 💡 Description
Add new documents, files, and videos to Training page. Specifics sent via email from Sheri Loftin (subjects "training website update" and "New videos for the training site")

**Comment by jordanpadams** [comment]
🕐 working this now, but not as straightforward as was hoped.

**Comment by tloubrieu-jpl** [comment]
Page updated on https://pds.nasa.gov/datastandards/training/
