### ISSUE TITLE
As a node user, I want guidelines for handling DOI metadata for accumulating data sets

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-tasks#26]
## 💪 Motivation
...so that I can use a consistent process that is used by most nodes and data sets.

## 📖 Additional Details

See [presentation](https://github.com/NASA-PDS/nasa-pds.github.io/files/8147528/doi-accumulating-data-doiwg-220224.pptx) from Joe M.

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect** 

## ⚙️ Engineering Details

- [x] Create new page under [DOI Support](https://nasa-pds.github.io/support/discipline_nodes/dois/index.html) for `Handling Accumulating Data Sets` with the content from the slides Joe M. presented at the DOI WG.

**Comment by viviant100** [comment]
@jordanpadams I added the process for accumulating data in https://pds-engineering.jpl.nasa.gov/content/doi (after "Processes for reserve or release a DOI" section).  Let me know if you want to make any changes. Thanks.

**Comment by jordanpadams** [comment]
@viviant100 looks good! made a few mods, but I think we can call this good.
* fix the diagram (wasn't appearing for some reason, Drupal is pretty awful for this...)
* add to TOC at top of page
* added PPTX to Drupal and updated link (was linking to JPL wiki)
