### ISSUE TITLE
improvement on citing page

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/portal-tasks#3]
## 🐛 Describe the bug

A few feedback on page https://pds-gamma.jpl.nasa.gov/datastandards/citing

- [x] Make the line shorter:

![image](https://user-images.githubusercontent.com/60993872/142454514-3c21594c-65ac-44aa-8acd-18317af8811e.png)

- [X] ~Revise the introduction to the search so that it is clear that we can search on part of lid.~
- [X] ~Revise the phrasing on the optional DOI on products (to be detailed, I can not spot it)~

**Comment by c-suh** [comment]
@tloubrieu-jpl let me know the revisions for the last two points [above](https://github.com/NASA-PDS/pds-site-app/issues/3#issue-1057552403) (for introduction and optional DOI on products, which I also cannot spot)

**Comment by jordanpadams** [comment]
Done and released
