### ISSUE TITLE
Data release manager pages missing login session check

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-tasks#31]
## 🐛 Describe the bug

Per https://itsd-jira.jpl.nasa.gov/servicedesk/customer/portal/16/DSIO-1979

## 📜 To Reproduce
From @acyu-jpl:

> These 2 files:
> /catalog_tools/data_release/em_release_info.cfm
> /catalog_tools/data_release/em_release_list.cfm
> 
> Are part of the data release manager function, specifically, Data Release Messages function which SHOULD require the user to go through catalog_tools/data_release/login.cfm page before they can access it, so this is a bug that I'll need to look into

## 🕵️ Expected behavior

Those pages should prompt for login if a user has not started a session.

**Comment by acyu** [comment]
the following files had been updated with user session checking at the beginning of the file, to make sure no anonymous user can access the system without login.  changes had been push to PDS Prod1 & Prod2
```
adm_data_producer_detail.cfm
adm_release_email.cfm
adm_release_manager.cfm
data_product_information.cfm
data_release_list.cfm
em_release_info.cfm
em_release_info_process.cfm
em_release_list.cfm
em_release_que.cfm
em_release_send.cfm
login.cfm
login_lostpw_response.cfm
```

**Comment by tloubrieu-jpl** [comment]
@viviant100 @acyu is there any updates on this ticket ?

**Comment by viviant100** [comment]
@tloubrieu-jpl this is resolved and the ticket can be closed.

**Comment by tloubrieu-jpl** [comment]
Thanks @viviant100
