### ISSUE TITLE
fix filenames for CASSINI_1B00_1300 in online archive

### ISSUE THREAD

**Issue by mace-space** [NASA-PDS/portal-tasks#38]
The validate tool does not have version CASSINI_1B00_1300 of the Cassini LDD in its library. This is required by @SheriAyn, who is providing the CLPS missions with example labels and their products. 

The example label for Array 3D: https://pds-rings.seti.org/pds4/bundles/cassini_vims_saturn/data_raw/14728xxxxx/1472800705.xml does not validate, with error:
```
System ID: https://pds.nasa.gov/pds4/mission/cassini/v1/PDS4_CASSINI_1B00_1300.sch
…
Engine name: Schematron 1.5
Severity: error
Description: 404 Not Found for: https://pds.nasa.gov/pds4/mission/cassini/v1/PDS4_CASSINI_1B00_1300.sch
```
If @lylehuber does not have version 1.3 of the Cassini Ingest_LDD file, @mit3ch can provide.

## Engineering Details
- [ ] update file names from `*Cassini*` to `*CASSSINI*`

**Comment by jordanpadams** [comment]
from user:
For the Cassini LDD files in https://pds.nasa.gov/pds4/mission/cassini/v1/ the filename base for this version of the LDD is `PDS4_Cassini_1B00_1300`. However, “Cassini” should be all upper case in the filenames. I spot checked the filenames for several other versions of this LDD. They all use the all-upper-case convention.

**Comment by jordanpadams** [comment]
@c-suh @acyu-jpl can we get this updated by end of week?

**Comment by c-suh** [comment]
@acyu-jpl I'll handle this, unless you've already started?
