### ISSUE TITLE
New PDS-AGU Web Page

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-tasks#4]
## 💡 Description

Per request from Sheri Loftin, we have a new web page to create for tracking the information needed for the PDS Booth at AGU.

Contents will be sent via JPL LFT.

Should be posted to https://pds.nasa.gov/collaborate/agu

**Comment by c-suh** [comment]
semi-status for this (Action 7b) in https://github.com/NASA-PDS/operations/issues/198#issuecomment-990539776

**Comment by c-suh** [comment]
@jordanpadams and @viviant100, please take a look at https://pds-gamma.jpl.nasa.gov/collaborate/agu. In trying to wrangle the information from Sheri's "Website layout.html" into a page consistent with the rest of the PDS site, there are more differences than I initially anticipated. I will be back later this evening or tomorrow to review comments and make the page operational for AGU come Monday.

**Comment by c-suh** [comment]
@jordanpadams and @viviant100, I realize that I may have deviated too much (and had also forgotten an image), so I moved the above link to https://pds-gamma.jpl.nasa.gov/collaborate/agu/alt.shtml and what was given to us (including a separate page for the wallpaper images) is now at https://pds-gamma.jpl.nasa.gov/collaborate/agu.

**Comment by jordanpadams** [comment]
@c-suh the former looks phenomenal! let's switch those around (maybe https://pds-gamma.jpl.nasa.gov/collaborate/agu/orig.shtml) and send your page out for feedback.

**Comment by c-suh** [comment]
@jordanpadams the pages have been switched! You'll have to do a hard refresh with clear cache for https://pds-gamma.jpl.nasa.gov/collaborate/agu/, but it should be fine for others who haven't been to the page yet.

**Comment by jordanpadams** [comment]
@c-suh since the conference starts Monday, let's actually just post it live on PDS.nasa.gov and we can make updates real-time based upon feedback

**Comment by c-suh** [comment]
@jordanpadams https://pds.nasa.gov/collaborate/agu/ is live!

**Comment by c-suh** [comment]
A couple fixes (add link to "What's New" and replace IPDA image) but otherwise approved by Joe Mafi. PR to be done.
