### ISSUE TITLE
add and update documents to Training page

### ISSUE THREAD

**Issue by c-suh** [NASA-PDS/portal-tasks#41]
## 💡 Description
Received multiple emails from Sheri with specifications and documents (new and replacement).
- Have to do: set up local process again for conversion and styling of received documents to posted pdfs
- Nice to do: found inconsistencies in filenames of example files

**Comment by jimmie** [comment]
Dealing with inconsistencies w/ file/dir naming, etc... is creating something of a time-sink. Hope to finish w.o. 8/29.

**Comment by c-suh** [comment]
New subsection seen under [Product Labels](https://pds.nasa.gov/datastandards/training/#product-labels) and new document is under "Organization of an Archive" subsection of [this section](https://pds.nasa.gov/datastandards/training/#what-is-pds4). Miscellaneous other fixes hidden amongst files. Let Sheri know and will reopen if there are any issues.

**Comment by c-suh** [comment]
She verified a few additions/fixes she would like as well as a couple forgotten link insertions.
