### ISSUE TITLE
Mars2020 Data Maps Bundle Broken Link

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-tasks#42]
## 🐛 Describe the bug

https://pds.nasa.gov/ds-view/pds/viewCollection.jsp?identifier=urn:nasa:pds:mars2020_rover_places:data_maps

[Mars 2020 Rover PLACES Bundle Online](https://pds.nasa.gov/ds-view/pds/%7BURL%7D) link is broken.

**Comment by rchenatjpl** [comment]
cr@p, 100% my fault, I'm fixing it

**Comment by jordanpadams** [comment]
@rchenatjpl has this been fixed?

**Comment by rchenatjpl** [comment]
Yes, I forgot about this, obviously.
