### ISSUE TITLE
[SECURITY] JQuery upgrade needed to avoid possible injection

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-tasks#47]
## Vulnerability
See email for scan results. Need to upgrade JQuery ASAP. This will most likely be in several places.

**Comment by c-suh** [comment]
"Hopefully resolves" is not actually resolved. Letting SAs know to test again.

**Comment by c-suh** [comment]
Re-scan is successful!

**Comment by jordanpadams** [comment]
@c-suh status: reopened due to vulnerability still in tool registry

**Comment by c-suh** [comment]
5 items addressed (main site, pb-search, data-search, dd-search, and tools-registry) and have asked Steve about the webhelp files.

**Comment by c-suh** [comment]
Steve is in the process of regenerating the WebHelp files.

**Comment by c-suh** [comment]
The webhelp files have been regenerated and updated, and I've let the appropriate persons know for a re-scan.

**Comment by jordanpadams** [comment]
closing this as done for time being. will re-open with specific task if still determined to be an issue

**Comment by tloubrieu-jpl** [comment]
@c-suh did you get a re-scan after this ticket was closed ?If not can you let @gxtchen know how to request it again ?

**Comment by c-suh** [comment]
@tloubrieu-jpl have just inquired, as I'm not sure if there was a rescan.

**Comment by c-suh** [comment]
The response:

> We have not heard anything, so I think we are OK for now.

**Comment by tloubrieu-jpl** [comment]
@gxtchen , @jordanpadams told us that you can use that information for the test validation: "we  have requested a re-scan to validate the change, since there was no answer it is considered the scan did not raise any vulnerability issue"
