### ISSUE TITLE
Update DataSet View to display DOI from label if there is no DOI for the product in our database

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-tasks#49]
## 💪 Motivation
Current ds-view uses DOI Search to only search PDS internal database for DOI. This improvement is to search using DOI Search first, and if it does not find anything, try the label metadata.

## 📖 Additional Details

Here are some examples of bundles with DOIs in their labels, but are not in our database (which is expected):
  https://pds.nasa.gov/ds-view/pds/viewBundle.jsp?identifier=urn:jaxa:darts:hyb2&version=3.0
  https://pds.nasa.gov/ds-view/pds/viewBundle.jsp?identifier=urn:jaxa:darts:hyb2_lidar&version=1.0
  https://pds.nasa.gov/ds-view/pds/viewBundle.jsp?identifier=urn:jaxa:darts:hyb2_nirs3&version=1.0
  https://pds.nasa.gov/ds-view/pds/viewBundle.jsp?identifier=urn:jaxa:darts:hyb2_tir&version=1.0

## 🦄 Related requirements
🦄 #7

**Comment by jordanpadams** [comment]
@c-suh ☝️ does this seem reasonable for this sprint?

**Comment by c-suh** [comment]
@jordanpadams I believe so. I will need some clarification at the next breakout regarding where/how to find the label metadata. Thank you!

**Comment by tloubrieu-jpl** [comment]
Catherine need to add back the code which was getting the DOI from the SOLR database as an alternative to the new code which get the DOI from the doi-service API.

**Comment by c-suh** [comment]
@jordanpadams please review these pages on GAMMA and let me know if it's good to go. If so, I will push these changes to the internal github and deploy on production. Thank you!

**Comment by jordanpadams** [comment]
@c-suh looks good to go. 💯
