### ISSUE TITLE
dataset status needs to be updated to better handle potential security vulnerability

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-tasks#55]
## 🐛 Describe the bug

Per [discussions on Slack #pdsen channel on 12/19](https://jpl.slack.com/archives/GCGR1R3A4/p1671475942781629), ds-status may not be sufficiently handling SQL Injection attempts.

## 📜 To Reproduce
See Slack discussion.

## 🕵️ Expected behavior

Cleans SQL injection attempt

**Comment by jordanpadams** [comment]
Status: Working through code

**Comment by c-suh** [comment]
Have implemented the changes but something broke the application and I'm trying to identify what exactly.

**Comment by c-suh** [comment]
Have the statement changes implemented and tested, and am verifying encoding.

**Comment by jimmie** [comment]
PR imminent

**Comment by c-suh** [comment]
PR created in internal JPL github and requested @jordanpadams as reviewer.

**Comment by jordanpadams** [comment]
added @nutjob4life @tloubrieu-jpl @anilnatha to the PR for review

**Comment by nutjob4life** [comment]
Approved over on enterprise

**Comment by c-suh** [comment]
Deployed to production! @jordanpadams and @tloubrieu-jpl, a note that the setup on one of the machines seemed to differ (newdsstatus versus dsstatus) and the application was 404, so I copied a conf file to connect the endpoint (I can provide details elsewhere). So, https://pds.nasa.gov/datasearch/ds-status/ is online! However, I thought Thomas had somehow disabled this. Is it still supposed to be disabled?

**Comment by jordanpadams** [comment]
@c-suh nope. I believe he just moved the WAR file from tomcat. Great stuff! And thanks to @nutjob4life for the PR review.

**Comment by nutjob4life** [comment]
Thanks! It's probably still a good idea to ask for an appscan of this. I left a link on enterprise github.

**Comment by c-suh** [comment]
SA ticket has been created to track appscan requests. Link is on enterprise github.
