### ISSUE TITLE
SQL permission on data-search

### ISSUE THREAD

**Issue by viviant100** [NASA-PDS/portal-tasks#56]
## 💡 Description
SQL permission issue (status code 200) on production (https://pds.nasa.gov/datasearch/data-search/).  See screenshot below:

![Screenshot 2023-01-09 at 10 19 37 AM](https://user-images.githubusercontent.com/22924433/211379599-01b8c365-b364-4c87-9f75-20c05148e7f5.png)

**Comment by c-suh** [comment]
Note: this is happening only on production.

**Comment by jordanpadams** [comment]
@viviant100 @c-suh @acyu-jpl FYI I updated this to be a bug with critical severity since the service does not work in operations.

**Comment by c-suh** [comment]
Fix is in the  repo and operational.
