### ISSUE TITLE
Add new MILabel video and presentation to training site

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-tasks#57]
## 💡 Description

From training lead:

> I have a new video and ppt presentation to add to the Tools section of the training site. Please remove the “PDS Viewer” entry and add:
>  
> MI Label and Velocity Templates
> Metadata Injector for PDS labels (MI Label) is a Java based command line tool that generates a PDS4 label from a template and a metadata file. The tutorial and video below use Apache Velocity templates and a simple text based metadata file to generate a PDS4 label.
>  
> Below that text add the ppt file attached and the video link: https://www.youtube.com/watch?v=muW726NyfQo&feature=youtu.be

**Comment by jordanpadams** [comment]
@c-suh let's add this to the stack for next sprint

**Comment by c-suh** [comment]
@jordanpadams, this has been added to a [new subsection](https://pds.nasa.gov/datastandards/training/#training-tools_mi-label-and-velocity-templates) under Tools. Does someone (you or Vivian or I) let the Training lead know via email?
