### ISSUE TITLE
Update PDS4 data dictionary links to be more consistent between Common and Local DD links

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-tasks#58]
## 💡 Description

From https://pds.nasa.gov/datastandards/documents/:
* `PDS Common Data Dictionary — Current Release` - should link to https://pds.nasa.gov/datastandards/dictionaries/<current>#pds-common and remove `(.html, .pdf)` for now. those are confusing and the Information Model Spec provides this info. We can link these from the data dictionaries page if we want to as the more appropriate place.
* `PDS Common Data Dictionary — All Releases` - should link to https://pds.nasa.gov/datastandards/dictionaries/index-versions.shtml
* `PDS Common Data Dictionary - Online Search` - should link to https://pds.nasa.gov/datastandards/documents/dd/common/current/ which should redirect to the latest `common` webhelp, e.g. https://pds.nasa.gov/datastandards/documents/dd/current/PDS4_PDS_DD_1J00/webhelp/common/
* `PDS Local Data Dictionaries - Online Search` - should link to https://pds.nasa.gov/datastandards/documents/dd/all/current/ which should redirect to the latest `all` webhelp, e.g. https://pds.nasa.gov/datastandards/documents/dd/current/PDS4_PDS_DD_1J00/webhelp/all/

those redirects may be a little convoluted, so we can see if there is a better way to redirect here.

**Comment by c-suh** [comment]
@jordanpadams please review these changes on gamma. If all looks good, I will put these on production. A note that I made the default index pages (inside datastandards/documents/dd and datastandards/documents/dd/v1) point to the online search, aka webhelp document for the PDS Common Data Dictionary. Would you like these to point to the current release or all releases instead?

**Comment by jordanpadams** [comment]
@c-suh the online search can always point to the latest version

**Comment by jordanpadams** [comment]
@c-suh and this looks great. 🚀

**Comment by c-suh** [comment]
The changes are on https://pds.nasa.gov/datastandards/documents/ and https://pds.nasa.gov/datastandards/documents/current-version.shtml.
