### ISSUE TITLE
links not working on data dictionary pages

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-tasks#6]
## 🐛 Describe the bug

From user:

> Thanks for pulling together the new release!  I see that the ML LDD appears here:
> 
> https://pds.nasa.gov/datastandards/dictionaries/index-1.17.0.0.shtml#ml
> 
> However, the links to the data dictionary files do not work, so we're not able to use it with the validate tool.  Could you check into this for us?

**Comment by c-suh** [comment]
@jordanpadams the fix is operational, albeit a bit of a mess with the new github (vs svn) setup. I'll have to wait til after Richard's data release to clean it up.

**Comment by jordanpadams** [comment]
thansk @c-suh do we know what happened or what is going on with SVN vs Github? I can try to help if it is something the scripts I wrote are doing

**Comment by c-suh** [comment]
@jordanpadams, it's more a matter of hammering out the process of multiple people using the staging environment - use of branches or just don't commit (if short term) or other? And separate but relevant, which github accounts are to be used on the machines and how that affects the processes (specific questions are queued up). I'd appreciate a separate meeting for this, but I'm assuming that other tasks are higher priority, i.e. AWS registry and overall AWS testing.

**Comment by jordanpadams** [comment]
> use of branches or just don't commit (if short term) or other?
we should follow the same paradigm as we did with SVN where we do not commit in-dev changes to main. However, for code review purposes, branch should be made offline so we can actually have the team look at it.

> And separate but relevant, which github accounts are to be used on the machines and how that affects the processes (specific questions are queued up).
@pds-ops should be the user for all website commits from the pds user on any of our PDS machines. We should setup the token, ssh keys, and git config user.name and user.email for the pds user on all machines so that is what is used to access Github.

**Comment by jordanpadams** [comment]
@c-suh I just set this on pds-gamma and production machines, but for the pds user, you will want to set these up on our AWS deployments so all commits for the website use the PDS Ops user:
```
$ git config --global user.name "PDS Ops Team"
git config --global user.email "pds-ops@jpl.nasa.gov"
```
