### ISSUE TITLE
Training page updates for Context_Area videos

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-tasks#61]
## 💡 Description

From Training coordinator:

I hope you aren’t very overwhelmed with work. I have three new videos to add to the training site as well as some documents to update. This isn’t something that has to be done immediately, so whenever you have a chance is fine; within the next two months would be great.
 
The Observation/Context Area (https://youtu.be/fTlwprf3VRI) video should be added to the “Observation Area” document. This document link should be added to the Context Product Label Structure section and the linked renamed to “Context Area”. See image:

![image](https://user-images.githubusercontent.com/33492486/225332447-071418d9-0c69-44e9-9ab1-d92a67de570f.png)

 
The Character Table (https://youtu.be/U_L_RX8B3Ag) and Delimited Table (https://youtu.be/2cyKRe5cNV0) videos should be added to their respective documents: “Filling Out the Table Character Data Structure” and “Filling Out the Table Delimited Data Structure”.
 
Here are the documents that need updating. All are updated on the google drive:
In the document “PDS4 Field Format Conventions”, in the note near the beginning, change the DDWG acronym to “PDS’s internal Data Design Working Group”. (https://docs.google.com/document/d/18ZREYJgTtNPClL2A79ePYGOy95wxbCbY/edit?usp=share_link&ouid=101942793507764462777&rtpof=true&sd=true)
I updated the “Filling Out the Table Character Data Structure” document to include the attribute “validation_format” under Field_Character. (https://docs.google.com/document/d/1WO4oMzfjsa48tRZCk4CwT-DCpY42LSUE/edit?usp=share_link&ouid=101942793507764462777&rtpof=true&sd=true)
I updated the “Filling Out the Table Delimited Data Structure” document to include “Line-Feed” as a record_delimiter value. (https://docs.google.com/document/d/15SWLTnwiphdvs1izx5nCrmu0VuhSI3PT/edit?usp=share_link&ouid=101942793507764462777&rtpof=true&sd=true)
 
I think that is everything. I hope you are doing well and let me know if you have any questions.

**Comment by c-suh** [comment]
PDFs have been updated as follows:
- [Context/Observation Area](https://pds.nasa.gov/datastandards/training/documents/Observation%20Area.pdf) for video
- [Character Table](https://pds.nasa.gov/datastandards/training/documents/Filling%20Out%20the%20Table%20Character%20Data%20Structure.pdf) for video and content
- [Delimited T able](https://pds.nasa.gov/datastandards/training/documents/Filling%20Out%20the%20Table%20Delimited%20Data%20Structure.pdf) for video and content
- [PDS4 Field Format Conventions](https://pds.nasa.gov/datastandards/training/documents/PDS4%20Field%20Format%20Conventions.pdf) for content

and the [Training page](https://pds.nasa.gov/datastandards/training/#product-labels) itself has an additional link for the updated Context/Observation Area PDF. Will email for review.

**Comment by c-suh** [comment]
Oops forgot the chain of command. @jordanpadams shall I or someone else let the Training contact know to review the page?
