### ISSUE TITLE
Links returning 404

### ISSUE THREAD

**Issue by anilnatha** [NASA-PDS/portal-tasks#68]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

After running a crawl of the pds.nasa.gov for sitemap generation purposes, the results of this crawl showed that the following URLs that were specified somewhere on the site are returning an HTTP status of `404` which can negatively affect our SEO:

- [x] https://pds.nasa.gov/datastandards/documents/dph/v03/PDS4_DataProvidersHandbook_20130321.pdf
- [x] https://pds.nasa.gov/datastandards/documents/dph/v03/PDS4_DataProvidersHandbook_20120901c.pdf
- [x] https://pds.nasa.gov/datastandards/documents/sr/v03/StdRef_4.0.8_130321.pdf
- [x] https://pds.nasa.gov/datastandards/documents/sr/v03/StdRef_4.0.6_main.pdf
- [x] https://pds.nasa.gov/datastandards/documents/glossary
- [x] https://pds.nasa.gov/datastandards/documents/jumpstart
- [x] https://pds.nasa.gov/datastandards/documents/ddt
- [x] https://pds.nasa.gov/home/providers/pds/doc/index.shtml
- [x] https://pds.nasa.gov/home/providers/tools/standards-reference.shtml
- [x] https://pds.nasa.gov/tools/phonebook/phonebook.cfm
- [x] https://pds.nasa.gov/datasearch/subscription-service/URL

### 🕵️ Expected behavior

The pages should not return a 404.

### 📜 To Reproduce

Simply visit any of the links mentioned in this post.

**Comment by jordanpadams** [comment]
@c-suh are these couple portal task tickets something @acyu-jpl could help with?

**Comment by c-suh** [comment]
@jordanpadams I believe I have addressed the check-listed items and have pulled this onto the machines. Does Anil need to regenerate a sitemap? Let me know any next steps; thank you!

**Comment by tloubrieu-jpl** [comment]
@c-suh All the links return 404 again... I am reopening this ticket

**Comment by c-suh** [comment]
@tloubrieu-jpl most of the links are not valid anymore. I assumed they were found by the program creating the sitemap and addressed these in the website code. Since these were faulty URLs, in commented-out code, or in extremely old and rarely used pages, I did not see a need to set up redirects, but would you like me to do so? Does verifying this task completion involve a regeneration of the sitemap?

**Comment by tloubrieu-jpl** [comment]
Hi @c-suh , so the fix was to remove the places where these url were used ?

**Comment by c-suh** [comment]
@tloubrieu-jpl yes, it was mostly removing URLs. I updated the link for the phonebook and a few others I found which were not listed above, e.g. https://pds.nasa.gov/tools/ddlookup/data_dictionary_lookup.cfm --> https://pds.nasa.gov/tools/dd-search/.

**Comment by tloubrieu-jpl** [comment]
Hi @gxtchen , I believe the best would be to test this ticket by having updated results for the link checker used by PDS Engineering Node. @c-suh found this page about the PDS Link checker. Could you investigate and add a non regression test checking for absence of broken links in the web site. Thanks.

**Comment by tloubrieu-jpl** [comment]
Hi @anilnatha , would you be able to propose us a good tool to check links on a regular basis for the web site ?
