### ISSUE TITLE
As a user, I want to see a DOI on all DOI landing pages

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-tasks#7]
... so that I can meet the requirements of DOI landing pages and improve the usability of the site.

## Engineering Details
Update ds-view query DOI Service for DOI instead of registry

## 💡 Description

Current PDS3 Data Set landing pages like [this one](https://pds.nasa.gov/ds-view/pds/viewDataset.jsp?dsid=A17L-L-TG-2-TRAVERSE-GRAVITY-V1.0) return this for DOI: `Unknown. Please contact the PDS Operator for assistance.`

Let's update this to:
1. First try to query the DOI Service for the DOI (**NOTE: For PDS3 data sets you will need to replace `/` with `*`**)
2. If exists, return it and link it like the viewBundle/viewCollection pages.
3. If it does not exist, return:
> Unknown. Please contact the PDS Help Desk for assistance

Where `PDS Help Desk` is a link that pops up the feedback widget. (_Note: currently functionality is kind of jarring to enable the pop-up. Ideally this should be an onClick event for the link that pops up the widget on the page the user is on. This is probably an event we should be using all over our website when we tell users to contact the Help Desk/Operator._)

---
UPDATE

Registry and the product metadata cannot be trusted. We should update all .JSP to query the DOI service for these DOIs.

**Comment by jordanpadams** [comment]
@acyu-jpl @c-suh see above. updated this ticket because we should now search DOI Service for DOIs from all JSP landing pages, not just the viewDataset.jsp.

**Comment by c-suh** [comment]
@jordanpadams this is now implemented on gamma for PDS3 and PDS4 products, e.g. 
- https://pds-gamma.jpl.nasa.gov/ds-view/pds/viewDataset.jsp?dsid=A17L-L-TG-2-TRAVERSE-GRAVITY-V1.0
- https://pds-gamma.jpl.nasa.gov/ds-view/pds/viewBundle.jsp?identifier=urn%3Anasa%3Apds%3Aa17lsg_raw_arcsav
- https://pds-gamma.jpl.nasa.gov/ds-view/pds/viewCollection.jsp?identifier=urn%3Anasa%3Apds%3Aa17lsg_raw_arcsav%3Adocument&version=1.0

Clarification for PDS4 products:
- Do we want similar behavior as before where if there is no DOI for a Collection, it'll look for the DOI of its parent bundle? (shown in last 2 links)

**Comment by jordanpadams** [comment]
as for the the pages, they look great!

**Comment by jordanpadams** [comment]
@c-suh found a bug:

https://pds.nasa.gov/ds-view/pds/viewDataset.jsp?dsid=vg1/vg2-j-iris-3-rdr-v1.0

works great

but if the URL is encoded, it fails:

https://pds.nasa.gov/ds-view/pds/viewDataset.jsp?dsid=vg1%2fvg2-j-iris-3-rdr-v1.0

There should be Java library to decode URL query parameters prior to/as you are parsing them. If unsure I would ping the pdsen channel.

**Comment by jordanpadams** [comment]
found something quickly here: https://www.baeldung.com/java-url-encoding-decoding not sure now up-to-date / accurate it is

**Comment by c-suh** [comment]
@jordanpadams yup, I undid the logic from https://github.com/NASA-PDS/software-issues-repo/issues/5#issuecomment-809741620 which was applied to PDS4 Collections and Bundles and am using the DOI Service for all the JSP pages.

OK, I will address the encoding bug. Thank you for catching that!

**Comment by c-suh** [comment]
@jordanpadams I'm unable to replicate the issue (tried Chrome, Safari, and Firefox), but I checked the parameter in a few places and it seems to be decoding correctly. If you want me to look into this further, there are several points of entry to these ds-view pages; from where did you get the URL? This might help me pinpoint the problem area.
- Keyword Search result
- Data Search result
- another ds-view page

**Comment by jordanpadams** [comment]
@c-suh oops! this works! you are a go for release!

**Comment by c-suh** [comment]
Issue on prod2 and all AWS machines (multiple reasons for the latter. Will seek clarity from relevant parties).

**Comment by tloubrieu-jpl** [comment]
This task is paused while @c-suh is staging files for I&T.

**Comment by c-suh** [comment]
further paused for AWS lift-and-shift. Noting https://github.com/NASA-PDS/portal-tasks/issues/19 just came in as it's related.

**Comment by c-suh** [comment]
Improved and deployed to all 6 machines (changes also incorporate those from issue #19). A note that this does not work on prem prod2 because the DOI service is not deployed there.  However, with the anticipated AWS lift-and-shift, that'll become irrelevant.
