### ISSUE TITLE
508 compliance updates for pds-engineering-wp.jpl.nasa.gov

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-tasks#77]
## 💡 Description

[PDS Engineering report.docx](https://github.com/NASA-PDS/portal-tasks/files/11983403/PDS.Engineering.report.docx)

**Comment by tloubrieu-jpl** [comment]
Hi @jordanpadams , do you think we can close this ticket if the web site had a green light for publication anyway ?

**Comment by jordanpadams** [comment]
Ready for DNS switchover
