### ISSUE TITLE
URL Encoding errors from Subscription Service pages

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-tasks#8]
## 🐛 Describe the bug

Per Markup Validation, looks like the pages being generated by the subscription service are encoding URLs incorrectly. Browsers are being more forgiving, but we should look into fixing this.

https://validator.w3.org/check?uri=https%3A%2F%2Fpds.nasa.gov%2Fdatasearch%2Fsubscription-service%2FSS-20220104.shtml&charset=%28detect+automatically%29&doctype=Inline&group=0&ss=1&verbose=1#line-208

<img width="1270" alt="Screen Shot 2022-01-10 at 11 53 05" src="https://user-images.githubusercontent.com/33492486/148852597-3b7b9da9-5c61-43e8-8816-854b3f0eb776.png">

## 🖥 System Info

---

**Comment by anilnatha** [comment]
The screenshot I shared was a test scan of a single page in the subscription service, if a copy of the full system scan report is needed, let me know.

**Comment by viviant100** [comment]
@acyu-jpl see above

**Comment by acyu** [comment]
@viviant100 I close to deploy the python script that will go through shtml file, parse the href link and update & to proper encoded value.  I will run the script on pds-gamma soon, once I have verify there is no issue with the output.

**Comment by anilnatha** [comment]
@acyu I can run a test using the software that reported the issue if you would like additional verification of your fixes. Just let me know.

**Comment by acyu** [comment]
Hi, @anilnatha, I ran the script on pds-gamma.jpl.nasa.gov/datasearch/subscription-service, quick spot check such on https://pds-gamma.jpl.nasa.gov/datasearch/subscription-service/PDS-Subscription-Service-01-Feb-07.shtml and https://pds-gamma.jpl.nasa.gov/datasearch/subscription-service/PDS-Subscription-Service-28-Jul-04.shtml show & has been properly converted.

Can you run the same test on pds-gamma to verify the fix?

**Comment by anilnatha** [comment]
Hi @acyu , I ran the test and it appears the the issue has been resolved regarding the links in the body of the page!

The scan found one more un-encoded URL in the head tag of the document for both of the URLs shared. Here is what was found on the first URL, that also applies to the second:

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/931107/152612131-77cbb2b8-1030-46c0-85a5-dad0eb0061d4.png">

**Comment by acyu** [comment]
Hi, @anilnatha I found the & in the include file, which is easy to update.  Please run the test again when you are available.  Thank you

**Comment by acyu** [comment]
file changes had been committed to push to prod1 & prod2

**Comment by viviant100** [comment]
@anilnatha Just to confirm the updates resolve your issue before we close the ticket.

**Comment by jordanpadams** [comment]
I think we wanted confirmation from @anilnatha on this, but let's close this out and can open a new ticket if it sneaks back up
