### ISSUE TITLE
Fix coldfusion vulnerability identified by ITSD

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-tasks#84]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

See ITSD report.

### 🕵️ Expected behavior

I expected no vulnerability

### 📜 To Reproduce

See ITSD report.

**Comment by jordanpadams** [comment]
ColdFusion has been patched and this has been fixed

**Comment by jordanpadams** [comment]
See email referencing "VDP-081" confirming closeout of issue on 8/28/23.

**Comment by tloubrieu-jpl** [comment]
@jordanpadams is that something I&T can check ? If yes how ?

**Comment by jordanpadams** [comment]
@tloubrieu-jpl No. This was a scan by IT Security. No idea how to replicate this scan

**Comment by jordanpadams** [comment]
Rationale for `i&t.skip` label ☝️
