### ISSUE TITLE
Add GSA's Digital Analytics Program tag to pds-engineering website

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-tasks#91]
### 💡 Description

Add the following to every page on the website (probably some Wordpress config/setting somewhere)

**Quick Guide**

Insert the following code inside the head tags (<head> </head>) of all pages on your site(s): 

```
<script async type="text/javascript" id="_fed_an_ua_tag" src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=NASA&subagency=JPL-pds-engineering"></script>
```

The script block must be inserted in a way that it appears on every page across the entire site, including sub-domains (e.g.: ed.gov and www.ed.gov and www2.ed.gov, etc.) and on-site search sub-domains (e.g.: find.ed.gov, searchjustice.usdoj.gov, search.nasa.gov).

### ⚔️ Parent Epic / Related Tickets

 - [x] update website
 - [x] notify JPL ITSD they can perform a rescan

**Comment by viviant100** [comment]
@c-suh we are being pinged again about this due to its deadline (5/31/24).  May we get this implemented in this sprint?

**Comment by c-suh** [comment]
@viviant100 sorry I completely missed this task and your comment. This has been done.

**Comment by jordanpadams** [comment]
Notified JPL ITSD. Done.
