### ISSUE TITLE
Broken links for 1.21.0.0 and 1.22.0.0

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-tasks#95]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

From https://pds.nasa.gov/datastandards/documents/examples/

https://pds.nasa.gov/datastandards/documents/examples/v1/DPH_Examples_V12200.zip
and 
https://pds.nasa.gov/datastandards/documents/examples/v1/DPH_Examples_V12100.zip

are broken.

### 🕵️ Expected behavior

I expected links to work

### 📜 To Reproduce

Go to links

**Comment by c-suh** [comment]
Fixed! It was a case typo in the filenames.

**Comment by jordanpadams** [comment]
Skipping I&T. Very simple fix. No additional testing needed.
