### ISSUE TITLE
Tool Registry no longer works with new Registry Servlet

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/portal-tasks#97]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

Tool registry fails when trying to query the Registry Servlet using Ajax

### 🕵️ Expected behavior

I expected the query to work

### 📜 To Reproduce

1. Go to Tool Registry on staging or test machine
2. Note the following error

<img width="778" alt="Screenshot 2024-08-13 at 3 48 47 PM" src="https://github.com/user-attachments/assets/76675ecb-f285-44d2-8875-76aef04fc107">

3. Note the request is: 
https://amazonaws.com/services/search/search?product-class=Product_Service&sort=service_name%20asc&wt=json&json.wrf=jQuery361015569558942856632_1723588753303&_=1723588753304

The servlet does not support `json.wrf`

---- 
UPDATE

The bug noted above is fixed by allowing `json.wrf` as a query parameter, but now the issue is since the Solr API only allows access to 1 requesthandler, services are being pre-filtered out of the results. We need to figure out an alternative solution for the servlet to support the Tool Registry.

**Comment by tloubrieu-jpl** [comment]
The PR will not work on the production registry.

**Comment by jordanpadams** [comment]
Closing this per merge to `prod-solr-upgrade` branch. We will definitely need to make sure we merge that to main. But this ticket is complete.
